package com.foodrescue.common.enums;

/** audit_logs.action */
public enum AuditAction {
    PAYMENT_SUCCESS, ORDER_CANCELLED, ORDER_EXPIRED, ORDER_COMPLETED, ORDER_NO_SHOW,
    REFUND_REQUESTED, REFUND_COMPLETED,
    PAYOUT_CREATED, PAYOUT_PAID, PAYOUT_CANCELLED,
    BATCH_CANCELLED,
    STORE_APPROVED, STORE_REJECTED, STORE_LOCKED, STORE_RATE_CHANGED,
    USER_LOCKED, USER_UNLOCKED, USER_PASSWORD_RESET
}
